name: Auto Update Repo Page

on:
  push:
    branches: [ main ]
    paths:
      - 'surge/*.ipa'
      - 'surge/*.tipa'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout ipa repo
        uses: actions/checkout@v4

      - name: Checkout repo page
        uses: actions/checkout@v4
        with:
          repository: 'wm0104/repo'
          token: ${{ secrets.GH_TOKEN }}
          path: './repo-page'

      - name: Run build script
        run: bash build_html.sh

      - name: Commit and Push
        run: |
          cd ./repo-page
          git config --global user.email 'action@github.com'
          git config --global user.name 'GitHub Action'
          git add index.html
          if ! git diff --staged --exit-code; then
            git commit -m 'Auto update app list'
            git push
          fi
